v0.3.0 Release Candidate
merixstudio/django-trench pull request #111
Opened 2021-08-27 09:27 UTC by allow-cookies

This pull request includes complete code refactoring to increase cohesion and get rid of coupling between serializers and views. Also the business logic was scattered across serializers, views and models - now the business logic lives in the commands, so responsibility segregation was increased.

More detailed list of changes:

* Support for Python >=3.6 only (older versions are not maintained anymore).
* Abandoned support of the `django-rest-framework-jwt` library as it is no longer maintained.
* Used `black` tool for auto code formatting.
* Type hints added.
* Backwards-compatible code refactoring and cleanup for better maintenance experience.
* Deactivation of primary MFA method would raise an error instead of randomly selecting new primary method from all active ones.
* Twilio backend client should be configured via environment variables instead of backend's configuration the `TWILIO_ACCOUNT_SID` and `TWILIO_AUTH_TOKEN`.

2021-11-16 19:13 UTC, lukzmu approved these changes
Approved. One thing you could do, is to fix the `codecov` drop, so the pipeline does not fail.

2021-11-16 19:13 UTC, lukzmu commented on testproject/settings.py
> +        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # noqa: E501
I really like the `E501` apart from `noqa` 👍🏻.

2021-11-18 22:57 UTC, mwrobel-merixstudio requested changes
everything looks fine, one last thing - we can drop this explicit assertions on `status_code` and use `rest_framework.status` consts

2021-11-18 22:57 UTC, mwrobel-merixstudio commented on testproject/tests/test_first_step_authentication.py
>      assert response.status_code == 200
in other tests we are using `rest_framework.status` const so we can do in this test too

2021-11-18 22:57 UTC, mwrobel-merixstudio commented on testproject/tests/test_first_step_authentication.py
> +    assert response.status_code == 400
in other tests we are using `rest_framework.status` const so we can do in this test too

2021-11-18 22:57 UTC, mwrobel-merixstudio commented on testproject/tests/test_first_step_authentication.py
>      assert response.status_code == 400
in other tests we are using `rest_framework.status` const so we can do in this test too

2021-11-18 22:57 UTC, mwrobel-merixstudio commented on testproject/tests/test_second_step_authentication.py
> +    assert response.status_code == 200
in other tests we are using `rest_framework.status` const so we can do in this test too

2021-11-18 22:57 UTC, mwrobel-merixstudio commented on testproject/tests/test_second_step_authentication.py
> +    assert response.status_code == 401
in other tests we are using `rest_framework.status` const so we can do in this test too

2021-11-18 22:57 UTC, mwrobel-merixstudio commented on testproject/tests/test_second_step_authentication.py
> +    assert response.status_code == 401
in other tests we are using `rest_framework.status` const so we can do in this test too

2021-11-18 22:57 UTC, mwrobel-merixstudio commented on testproject/tests/test_second_step_authentication.py
> +    assert response.status_code == 401
in other tests we are using `rest_framework.status` const so we can do in this test too

2021-11-18 22:57 UTC, mwrobel-merixstudio commented on testproject/tests/test_second_step_authentication.py
>      assert response.status_code == 400
in other tests we are using `rest_framework.status` const so we can do in this test too

2021-11-18 22:57 UTC, mwrobel-merixstudio commented on testproject/tests/test_second_step_authentication.py
>      assert response.status_code == 400
in other tests we are using `rest_framework.status` const so we can do in this test too

2021-11-18 22:57 UTC, mwrobel-merixstudio commented on testproject/tests/test_second_step_authentication.py
>      assert response.status_code == 400
in other tests we are using `rest_framework.status` const so we can do in this test too

2021-11-18 22:57 UTC, mwrobel-merixstudio commented on testproject/tests/test_second_step_authentication.py
> +    assert response.status_code == 204
in other tests we are using `rest_framework.status` const so we can do in this test too

2021-11-18 22:57 UTC, mwrobel-merixstudio commented on testproject/tests/test_second_step_authentication.py
> +    assert response.status_code == 204
in other tests we are using `rest_framework.status` const so we can do in this test too

2021-11-18 22:57 UTC, mwrobel-merixstudio commented on testproject/tests/test_second_step_authentication.py
>      assert response.status_code == 400
in other tests we are using `rest_framework.status` const so we can do in this test too

2021-11-18 22:57 UTC, mwrobel-merixstudio commented on testproject/tests/test_second_step_authentication.py
>      assert response.status_code == 400
in other tests we are using `rest_framework.status` const so we can do in this test too

2021-11-18 22:57 UTC, mwrobel-merixstudio commented on testproject/tests/test_second_step_authentication.py
>      assert response.status_code == 400
in other tests we are using `rest_framework.status` const so we can do in this test too

2021-11-18 22:57 UTC, mwrobel-merixstudio commented on testproject/tests/test_second_step_authentication.py
>      assert response.status_code == 200
in other tests we are using `rest_framework.status` const so we can do in this test too

2021-11-18 22:57 UTC, mwrobel-merixstudio commented on testproject/tests/test_second_step_authentication.py
>      assert response.status_code == 400
in other tests we are using `rest_framework.status` const so we can do in this test too

2021-11-18 22:57 UTC, mwrobel-merixstudio commented on testproject/tests/test_second_step_authentication.py
>      assert response.status_code == 200
in other tests we are using `rest_framework.status` const so we can do in this test too

2021-11-18 22:57 UTC, mwrobel-merixstudio commented on testproject/tests/test_second_step_authentication.py
> +    assert response.status_code == 401
and so on ;) so you can just use `rest_framework.status` consts in all tests on each `status_code` assertion in all tests

2021-11-19 09:49 UTC, mwrobel-merixstudio approved these changes
looks good :)

2021-11-29 13:51 UTC, merged