Add fix for type aliasing issue with get_user_model() assignement and mypy
merixstudio/django-trench pull request #184
Opened 2022-11-02 18:10 UTC by jhurej

2022-11-02 19:10 UTC, jhurej commented
Probably I will revert drf downgrade becuase of this PR https://github.com/merixstudio/django-trench/pull/162

2022-11-03 13:56 UTC, wmaciejewskimer approved these changes

2022-11-04 08:05 UTC, allow-cookies requested changes

2022-11-04 08:05 UTC, allow-cookies commented on trench/backends/application.py
> +User: settings.AUTH_USER_MODEL = get_user_model()
`settings.AUTH_USER_MODEL` doesn't seem like a proper type definition. I'm aware that `mypy` doesn't report an issue after adding this value as a type hint but it's not a valid argument as you can add:

```python
User: settings.WHATEVER = get_user_model()
```

and `mypy` will report that everything is fine as well.

The `django.contrib.auth.models.AbstractUser` would be a better fit here as a type hint.

2022-11-04 08:52 UTC, wmaciejewskimer commented on trench/backends/application.py
> +User: settings.AUTH_USER_MODEL = get_user_model()
Good point, fixed in new commit

2022-11-04 09:03 UTC, allow-cookies approved these changes
Looks good 👍

2022-11-04 09:05 UTC, merged